const createUsersTableApi = require('./migrations/users')
const createFavoriteCafesTableApi = require('./migrations/favorite-cafes')
const createPaymentInformationsTableApi = require('./migrations/payment-informations')
const createInvoicesTableApi = require('./migrations/invoices')
const createPaymentMethodsTableApi = require('./migrations/payment-methods')
const createReviewsTableApi = require('./migrations/reviews')
const createRepliesTableApi = require('./migrations/replies')
const createCafesTableApi = require('./migrations/cafes')
const createPlansTableApi = require('./migrations/plans')
const createCafeTagsTableApi = require('./migrations/cafe-tags')
const createTagsTableApi = require('./migrations/tags')
const createArticlesTableApi = require('./migrations/articles')
const createArticleContentsTableApi = require('./migrations/article-contents')
const createContentTypesTableApi = require('./migrations/content-types')
const createPublicationStatusTableApi = require('./migrations/publication-status')

function dbApi(server) {
  server.use('/api/v1/create-users-table', createUsersTableApi)
  server.use('/api/v1/create-plans-table', createPlansTableApi)
  server.use('/api/v1/create-cafes-table', createCafesTableApi)
  server.use('/api/v1/create-favorite-cafes-table', createFavoriteCafesTableApi)
  server.use('/api/v1/create-tags-table', createTagsTableApi)
  server.use('/api/v1/create-cafe-tags-table', createCafeTagsTableApi)
  server.use('/api/v1/create-reviews-table', createReviewsTableApi)
  server.use('/api/v1/create-replies-table', createRepliesTableApi)
  server.use('/api/v1/create-publication-status-table', createPublicationStatusTableApi)
  server.use('/api/v1/create-content-types-table', createContentTypesTableApi)
  server.use('/api/v1/create-articles-table', createArticlesTableApi)
  server.use('/api/v1/create-article-contents-table', createArticleContentsTableApi)
  server.use('/api/v1/create-payment-methods-table', createPaymentMethodsTableApi)
  server.use('/api/v1/create-payment-informations-table', createPaymentInformationsTableApi)
  server.use('/api/v1/create-invoices-table', createInvoicesTableApi)
}

module.exports = dbApi
